<?xml version="1.0"?>
<!--
  TO BE CHANGED TO EDRONE.xacro due to changes in arm length and extra motors
-->

<robot name="edrone" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Properties (Taken from Novel Dynamic Inversion Architecture Design for Quadrocopter Control by Jian Wang et al.) -->
  <xacro:property name="namespace" value="$(arg mav_name)" />
  <xacro:property name="rotor_velocity_slowdown_sim" value="10" />
  <xacro:property name="use_mesh_file" value="true" />
  <!-- <xacro:property name="mesh_file" value="package://rotors_description/meshes/crazyflie2.dae" /> -->
  <xacro:property name="mesh_file" value="package://rotors_description/meshes/edrone_frame.stl" />
  <xacro:property name="mass" value="0.027" /> <!-- [kg] -->
  <xacro:property name="body_width" value="0.11" /> <!-- [m] -->
  <xacro:property name="body_height" value="0.036" /> <!-- [m] -->
  <xacro:property name="mass_rotor" value="0.00033" /> <!-- [kg] -->
  <xacro:property name="arm_length" value="0.065" /> <!-- [m] -->
  <!-- <xacro:property name="rotor_offset_top" value="0.024" /> --> <!-- [m] -->
  <xacro:property name="rotor_offset_top" value="0.015" />
  <xacro:property name="motor_offset_top" value="-0.015" />
  <xacro:property name="radius_rotor" value="0.0225" /> <!-- [m] -->
  <!-- Forster's -->
  <!-- [kg m/s^2] -->
  <xacro:property name="motor_constant" value="1.28192e-08" />
  <!-- <xacro:property name="motor_constant" value="1e-07" />  -->
  <xacro:property name="moment_constant" value="5.964552e-03" /> <!-- [m] -->
  <xacro:property name="time_constant_up" value="0.0125" /> <!-- [s] -->
  <xacro:property name="time_constant_down" value="0.025" /> <!-- [s] -->
  <xacro:property name="max_rot_velocity" value="2618" /> <!-- [rad/s] -->
  <xacro:property name="rotor_drag_coefficient" value="8.06428e-05" />
   <xacro:property name="sqrt2by2" value="0.707106781186" />
  <xacro:property name="rolling_moment_coefficient" value="0.000001" />

  <!-- Property Blocks -->
  <xacro:property name="body_inertia">
    <inertia ixx="1.657171e-06" ixy="0.0" ixz="0.0" iyy="1.657171e-06" iyz="0.0" izz="2.9261652e-06" />
  </xacro:property>

  <!-- inertia of a single rotor, assuming it is a cuboid. Height=0.4mm, width=0.8mm -->
  <xacro:property name="rotor_inertia">
    <xacro:box_inertia x="${radius_rotor}" y="0.001" z="0.0003" mass="${mass_rotor*rotor_velocity_slowdown_sim}" />
  </xacro:property>

  <!-- Included URDF Files -->
  <xacro:include filename="$(find rotors_description)/urdf/multirotor_base.xacro" />

  <!-- Instantiate multirotor_base_macro once -->
  <xacro:multirotor_base_macro
    robot_namespace="${namespace}"
    mass="${mass}"
    body_width="${body_width}"
    body_height="${body_height}"
    use_mesh_file="${use_mesh_file}"
    mesh_file="${mesh_file}">
    <xacro:insert_block name="body_inertia" />
  </xacro:multirotor_base_macro>

  <!-- Instantiate rotors -->
  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="front_right"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="0"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Red"
    use_own_mesh="false"
    mesh="">
    <origin xyz="${sqrt2by2 * arm_length} ${sqrt2by2 * arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>
  <xacro:vertical_motor 
    radius_rotor="${radius_rotor}"
    motor_number="0"
    parent="${namespace}/base_link"
    robot_namespace="${namespace}"
    suffix="front_right">
    <origin xyz="${sqrt2by2 * arm_length} ${sqrt2by2 * arm_length} ${motor_offset_top}" rpy="1.570796327 0 0"/>
  </xacro:vertical_motor>


  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="front_left"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="1"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Blue"
    use_own_mesh="false"
    mesh="">
    <origin xyz="-${sqrt2by2 * arm_length} ${sqrt2by2 * arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>
  <xacro:vertical_motor 
    radius_rotor="${radius_rotor}"
    motor_number="1"
    parent="${namespace}/base_link"
    robot_namespace="${namespace}"
    suffix="back_left">
    <origin xyz="-${sqrt2by2 * arm_length} ${sqrt2by2 * arm_length} ${motor_offset_top}" rpy="1.570796327 0 0"/>
  </xacro:vertical_motor>

  <xacro:vertical_rotor robot_namespace="${namespace}"
    suffix="back_left"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="2"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Red"
    use_own_mesh="false"
    mesh="">
    <origin xyz="-${sqrt2by2 * arm_length} -${sqrt2by2 * arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>
  <xacro:vertical_motor 
    radius_rotor="${radius_rotor}"
    motor_number="2"
    parent="${namespace}/base_link"
    robot_namespace="${namespace}"
    suffix="front_left">
    <origin xyz="-${sqrt2by2 * arm_length} -${sqrt2by2 * arm_length} ${motor_offset_top}" rpy="1.570796327 0 0"/>
  </xacro:vertical_motor>

  <xacro:vertical_rotor robot_namespace="${namespace}"
    suffix="back_right"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="3"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Blue"
    use_own_mesh="false"
    mesh="">
    <origin xyz="${sqrt2by2 * arm_length} -${sqrt2by2 * arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>
  <xacro:vertical_motor 
    radius_rotor="${radius_rotor}"
    motor_number="3"
    parent="${namespace}/base_link"
    robot_namespace="${namespace}"
    suffix="back_right">
    <origin xyz="${sqrt2by2 * arm_length } -${sqrt2by2 * arm_length} ${motor_offset_top}" rpy="1.570796327 0 0"/>
  </xacro:vertical_motor>

</robot>
